Fix error message printout

diff --git a/.github/workflows/cmake_install_macos.yml b/.github/workflows/cmake_install_macos.yml
--- a/.github/workflows/cmake_install_macos.yml
+++ b/.github/workflows/cmake_install_macos.yml
@@ -26,4 +26,5 @@ jobs:
         touch test.cpp
         echo "#include <dsm/dsm.hpp>" >> test.cpp
         echo "int main() {}" >> test.cpp
-        g++ test.cpp -std=c++20 && echo "Compiled successfully" || echo "Cannot include dsm"
+        g++ test.cpp -std=c++20 && echo "Compiled successfully" \
+                                || (echo "Cannot include dsm" ; exit 1)
