Add conditional print

diff --git a/.github/workflows/cmake_install.yml b/.github/workflows/cmake_install.yml
--- a/.github/workflows/cmake_install.yml
+++ b/.github/workflows/cmake_install.yml
@@ -29,4 +29,4 @@ jobs:
         touch test.cpp
         echo "#include <dsm/dsm.hpp>" >> test.cpp
         echo "int main() {}" >> test.cpp
-        g++ test.cpp -std=c++20
+        g++ test.cpp -std=c++20 && echo "Compiled successfully" || echo "Cannot include dsm"
